import bpy,json,os,hashlib,ast,math
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view
R=os.path.dirname(os.path.abspath(__file__));P=json.load(open(R+'/site_plan.json'));out={};checks={}
tr=ast.parse(open(R+'/../../Phase5/RivalHQs/integrate_pallas.py').read());exec(compile(ast.Module(body=[n for n in tr.body if isinstance(n,ast.FunctionDef) and n.name=='sig'],type_ignores=[]),'sig','exec'))
tr=ast.parse(open(R+'/../../Phase5/RivalHQs/verify_final.py').read());exec(compile(ast.Module(body=[n for n in tr.body if isinstance(n,ast.FunctionDef) and n.name in ['prepare','sight']],type_ignores=[]),'visibility','exec'))
bpy.ops.wm.open_mainfile(filepath=R+'/../../Phase5/RivalHQs/Blender/Atlantis_Phase5_Masterplan.blend');base={o.name:sig(o) for o in bpy.context.scene.objects}
bpy.ops.wm.open_mainfile(filepath=R+'/Blender/Atlantis_Phase6_Masterplan.blend');s=bpy.context.scene;bpy.context.view_layer.update();changed=[n for n,h in base.items() if not bpy.data.objects.get(n) or sig(bpy.data.objects[n])!=h];checks['all_original_geometry_transforms_metadata_preserved']=not changed;out['changed_original_objects']=changed
obs=[o for o in s.objects if o.type=='MESH' and not o.hide_render and not any(c.hide_render for c in o.users_collection)];build=[o for o in bpy.data.collections['Startup_Buildings'].objects if o.type=='MESH'];pts=[o.matrix_world@Vector(p) for o in build for p in o.bound_box];checks['building_bounds_inside_startup']=all(-720<=p.x<=-200 and -540<=p.y<=-140 for p in pts)
checks['five_progression_slots']=all(bpy.data.objects.get('Progression_'+n) for n in ['Loft','SmallOffice','Office','SmallBuilding','BigBuilding']);checks['all_buildings_below_55m']=all(a['height']+1.3<55 for a in P['sites']);out['measured_building_heights_above_entrance']={a['id']:max((o.matrix_world@Vector(c)).z for o in bpy.data.objects['Startup_'+a['id']].children if o.type=='MESH' for c in o.bound_box)-a['position'][2] for a in P['sites']};checks['three_social_shells']=sum(a['typology']=='Startup_Cafe' for a in P['sites'])==3
audit=json.load(open(R+'/build_audit.json'));checks['all_38_frontages_connected']=len(audit['frontage_paths'])==len(P['sites']);checks['new_paths_3m_clear_width']=all(a['width']>=3 for a in audit['frontage_paths']);checks['new_paths_grade_at_most_5percent']=all(a['grade']<=.05 for a in audit['frontage_paths']);out['metrics']={'visible_meshes':len(obs),'visible_triangles':sum(len(p.vertices)-2 for o in obs for p in o.data.polygons),'building_meshes':len(build),'building_triangles':sum(len(p.vertices)-2 for o in build for p in o.data.polygons),'building_materials':len({m.name for o in build for m in o.data.materials}),'building_count':len(P['sites']),'unique_building_mesh_data':len({o.data.name for o in build}),'height_range':[min(out['measured_building_heights_above_entrance'].values()),max(out['measured_building_heights_above_entrance'].values())]}
views=['Founder_To_City','TheSpire_StartupSightline','VentureHall_ToSpire','MediaDistrict_ToSpire','TechCore_Skyline','UnicornHeights_View']
for phase,path in [('Phase5',R+'/../../Phase5/RivalHQs/Blender/Atlantis_Phase5_Masterplan.blend'),('Phase6',R+'/Blender/Atlantis_Phase6_Masterplan.blend')]:
 s,dep=prepare(path);points=[]
 for o in s.objects:
  if o.type=='MESH' and o.name.startswith('TheSpire_'):points += [o.matrix_world@v.co for v in o.data.vertices if (o.matrix_world@v.co).z>265]
 points=points[::max(1,len(points)//40)];out[phase+'_spire_samples']={n:sum(sight(s,dep,bpy.data.objects[n],p,'TheSpire_') for p in points) for n in views}
checks['six_spire_views_not_worsened']=all(out['Phase6_spire_samples'][n]>=out['Phase5_spire_samples'][n] for n in views)
cam=bpy.data.objects['StartupRow_Flashpoint'];hits=sum(sight(s,dep,cam,(430+dx,-240,14+75*f),'Flashpoint_') for dx in [-4,0,4] for f in [.4,.6,.8,.95]);checks['startup_flashpoint_visible']=hits>0;out['flashpoint_hits_of_12']=hits
basefiles=json.load(open(R+'/preservation_baseline.json'));checks['protected_files_unchanged']=all(hashlib.sha256(open(p,'rb').read()).hexdigest()==h for p,h in basefiles.items());out['protected_file_count']=len(basefiles);out['checks']=checks;json.dump(out,open(R+'/verification.json','w'),indent=2);print(json.dumps(out,indent=2))
