from pathlib import Path
import json
R=Path(__file__).resolve().parent;repo=R.parents[3];report=repo/'Documentation/Atlantis/PHASE5_RIVAL_HQ_PRODUCTION_REPORT.md'
load=lambda p:json.loads(p.read_text())
metrics=load(R/'final_metrics.json');v=load(R/'verification.json');contracts=load(R/'../../Phase4/Rivals/future_higgsfield_contracts.json');names=['PallasAI','NorthwindLabs','Flashpoint']
lines=['# Atlantis Phase 5 — Rival HQ production report','', 'Date: 2026-09-10. Scope: three canonical rival headquarters and a new Phase 5 Blender masterplan. No runtime integration.', '', 'The final HQs use source-informed architectural reconstruction in Blender. The generated GLBs are preserved as references; their original noisy surfaces and 4K textures are not used in the final exports. This is reconstruction, not a claim of lossless decimation or unchanged generated topology.','', '## Phase 4 contracts and final placement','', '| Company | Canonical slot / district | World origin (m) | Initial maximum (m) | Final dimensions (m) | Growth envelope (m) |','|---|---|---|---|---|---|']
fmt=lambda a:' × '.join(f'{x:g}' for x in a)
for n,c in zip(names,contracts):lines.append(f"| {c['displayName']} | {c['slotID']} / {c['district']} | {c['worldPosition']} | {fmt(c['initialMaximumFootprint'])} | {fmt(metrics[n]['dimensions'])} | {fmt(c['absoluteUpgradeEnvelope'])} |")
lines += ['', 'Approved final height ranges are Pallas 120–170 m, Northwind 100–130 m and Flashpoint 55–90 m; exact chosen targets are 160, 115 and 75 m respectively.', '', 'Each production root remains parented to its original canonical semantic locator and slot. One Blender unit is one metre. Standalone pivots are the footprint center at ground elevation (0,0,0); all final object rotations are zero and scales are (1,1,1). Main facades face −Y in Blender / +Z in glTF. No parcel moved.', '', '## Generation and source audit','', 'Generation order was Pallas → accepted → Northwind → accepted → Flashpoint. Pallas and Flashpoint each needed two candidates; Northwind needed one. An initial Pallas prompt exceeded the 1,024-character service limit and failed before creating a candidate. The five actual candidate jobs completed.', '', '| Source | Bytes | Source dimensions (arbitrary units) | Meshes / triangles / materials | Textures | Non-manifold edges after seam weld |', '|---|---:|---|---|---|---:|']
for n in names:
 for p in sorted((R/n/'Source').glob('source_audit*.json')):
  a=load(p);lines.append(f"| {n}/{a['filename']} | {a['bytes']:,} | {fmt(a['dimensions'])} | {a['meshes']} / {a['triangles']:,} / {a['materials']} | {a['textures']} × 4096² RGBA | {sum(o['nonmanifold'] for o in a['objects'])} |")
lines += ['', 'All raw sources import as a single unparented mesh at object origin (0,0,0), zero rotation and unit scale, with arbitrary centered geometry bounds rather than a ground pivot. Exact bounds, component sizes, hierarchy and texture names are retained in each source_audit JSON. All source audits found zero zero-area faces. Each source has color, normal and ORM maps: approximately 192 MiB decoded RGBA total, excluding mipmaps and GPU compression. These maps have distinct roles, not duplicate image copies.', '', 'Pallas candidate 1 had an oversized campus, ornate crown and detached sign. Candidate 2 supplied the disciplined tower, bronze fins and restrained crown direction. A uniformly scaled and rotated tower cleanup study was attempted, but corrugation remained; the final tower was rebuilt with planar tapered rings, formal podium, fins, crown and entrance. The repaired study is retained only in hidden staging.', '', 'Northwind candidate 1 supplied the pale frame, cool glazing, technical roof and connected research wing. Its campus footprint was too broad at the target height. Reconstruction retained that composition in a 56 × 50 m foundation, with modular floor bands and an offset research tower.', '', 'Flashpoint candidate 1 generated a two-building streetscape with trees, road, vehicle and oversized billboard panels, so its concept was rejected. The selected second candidate and the final reconstruction are described in Flashpoint/Source/production_notes.md.', '', '## Cleanup and final independent exports','', '| HQ | Chosen source height → final height | Source → final triangles | Reduction* | Meshes | Materials | Textures | GLB bytes |','|---|---|---|---:|---:|---:|---:|---:|']
for n in names:
 a=load(R/n/'Source'/('source_audit.json' if n=='NorthwindLabs' else 'source_audit_candidate2.json'));m=metrics[n]
 lines.append(f"| {n} | {a['dimensions'][2]:.6f} → {m['dimensions'][2]:g} m | {a['triangles']:,} → {m['triangles']:,} | {(1-m['triangles']/a['triangles'])*100:.1f}% | {m['meshes']} | {m['materials']} | {m['textures']} | {m['bytes']:,} |")
lines += ['', '*Reduction compares source and reconstructed triangle counts; it is not a decimation quality metric.', '', 'The final meshes have outward closed component geometry, no non-manifold edges after UV-seam welding, no zero-area faces, positive signed volume and clean transforms. Architectural components deliberately overlap at structural joints; this is not a Boolean-unioned watertight building solid. Reconstructed geometry removes generated disconnected junk, streetscape props, irregular facade surfaces and unnecessary subdivisions. Flat architectural faces avoid damaged source smoothing. No displacement or normal textures remain.', '', 'Each GLB was exported and freshly reimported. Final .blend files were saved from these independent imports. The final exports contain no textures and therefore no unused or duplicate texture maps. Original 4K maps remain in raw sources and hidden source staging in the authoring master, which is not a mobile runtime payload.', '', '## Semantic targets and lighting','']
for n in names:lines.append(f"- {n}: "+', '.join('`'+t+'`' for t in metrics[n]['semantic_targets'])+'.')
lines += ['', 'Material families:', '']
for n in names:lines.append('- '+n+': '+', '.join(metrics[n]['material_names'])+'.')
lines += ['', 'Targets retain separate objects, material families, UV maps and semantic_target / dynamic_material_target metadata. The old hidden blockouts retain their original names; where Blender assigns a .001 suffix to a new master object, semantic_target carries the exact canonical name. Standalone GLBs and .blend files use exact unsuffixed names. Displays are blank and no permanent text is required for architectural identity.', '', 'Pallas uses controlled warm lobby/crown identity; Northwind uses restrained cool lab and entrance illumination; Flashpoint uses concentrated warm accent and launch/podium activity. Day and night Blender renders were visually reviewed. Material families support future light changes for morning/noon/evening/night, but no time system, rival state behavior, animation or simulation authority is implemented.', '', '## Future growth capacity','', '| HQ | Additional width / depth / height available (m) | Unoccupied growth-envelope plan area (m²) |', '|---|---|---:|']
for n in names:lines.append(f"| {n} | {fmt(metrics[n]['remaining_growth_dimensions'])} | {metrics[n]['remaining_growth_plan_area_m2']:g} |")
lines += ['', 'These are bounding-envelope differences, not promises of usable construction area or a specific upgrade design. Existing Phase 4 road and neighbor clearances remain applicable because all initial assets fit inside the original approved footprints and all growth envelopes and roads remain unchanged.', '', '## Sightlines and skyline','', 'The table below records sampled visibility from fixed review cameras: Strong = at least 6/12 samples, Partial = 1–5, Hidden = zero. These samples are a reproducible visibility aid; visual review remains necessary and does not guarantee visibility from every position in a district.', '', '| Fixed camera | Pallas | Northwind | Flashpoint |','|---|---|---|---|']
for cam in next(iter(v['sampled_visibility'].values())):lines.append('| '+cam+' | '+' | '.join(v['sampled_visibility'][n][cam]['rating'] for n in names)+' |')
lines += ['', 'Visual review supplements the sampled table: Pallas shows a partial crown/edge from Founder even though its centerline sample rays miss the exposed sliver. Flashpoint is Partial in the additional Commerce approach and Tech approach views, while Strong from the Startup approach. Northwind is Hidden from the fixed Startup/Media ground views and Strong at the research edge. No existing buildings were moved to force visibility.', '', 'The Spire remains the 280 m primary landmark. Pallas is an important 160 m corporate tower, visibly credible from Venture, with a shorter and distinct bronze crown. Northwind is a 115 m research tower on the research edge; existing foreground towers obscure it from some distant ground-level views. Flashpoint remains a 75 m Commerce company near the startup progression route. The 145 m Tech.com Tower, 47 m Signal TV and 41.4 m Venture Hall keep their existing geometry, placement and roles. Media retains rival skyline presence without moving its landmarks.', '', '| Established Spire view | Phase 4 visible crown samples | Phase 5 visible crown samples |','|---|---:|---:|']
for cam,a in v['Phase4_spire_crown_samples'].items():lines.append(f"| {cam} | {a} | {v['Phase5_spire_crown_samples'][cam]} |")
lines += ['', 'Crown samples use actual upper Spire surface points, including correct orthographic ray origins and exclusion of hidden staging/blockouts. Founder-to-Spire and the five other established views are not worsened. The pre-existing support massing still occludes parts of the lower Spire; this pass does not redesign that composition.', '', '## Validation and preservation','', f"{sum(v['checks'].values())}/{len(v['checks'])} combined checks passed; {v['protected_file_count']} protected file hashes match the baseline. Every original Phase 4 object retains its local transform, parent, custom metadata, mesh geometry and material references. Only the three old HQ blockout mesh visibility flags are disabled in the new master after the rival-specific checks passed.", '', 'Phase 0 geography, terrain, bay, roads, bridges, district boundaries, Founder Garage slot, Player Unicorn slot, The Spire, Venture Hall, Tech.com and Signal TV are preserved. Phase 0–4 files were not edited. Garage V7, app/runtime, GameStore and save version 19 were untouched. Existing unrelated dirty app, test, project and scheme changes were preserved. No commits or pushes were made.', '', 'This is a Blender-only asset pass: no Xcode build, XCTest, simulator or device run was performed. Blender visual review does not establish RealityKit performance or on-device correctness. Simulator/device verification remains a later human acceptance step; these GLBs are not yet promoted to RealityKit production.', '', '## Six final acceptance answers','', '1. **Yes** — Pallas reads as an established global AI powerhouse through its height, formal podium, disciplined taper and bronze crown.', '2. **Yes** — Northwind reads as technically rigorous and research-driven through its modular frame, offset tower and connected lab podium.', '3. **Yes** — Flashpoint reads as an aggressive high-growth rival through its asymmetric silhouette, sharper rhythm and concentrated launch-facing accent.', '4. **Yes** — all three are distinguishable without text labels in the same-scale architecture comparison.', '5. **Yes** — the assets fit their approved parcels and preserve the masterplan and Founder-to-Spire sightline.', '6. **Yes** — Atlantis can now represent its three canonical rivals as distinct physical companies in the city.', '', 'These are visual production judgments supported by the saved review renders and geometry/placement checks, not runtime or user acceptance claims.', '', '## Created / changed Phase 5 files','', 'All paths below are relative to the repository. Intermediate candidates, preservation snapshots, raw sources and review renders are retained for traceability. The final deliverables are the three Atlantis_*_HQ_v1 pairs and Blender/Atlantis_Phase5_Masterplan.blend.','']
paths=sorted(p for p in R.rglob('*') if p.is_file());lines += ['- `'+str(p.relative_to(repo))+'`' for p in paths];lines+=['- `Documentation/Atlantis/PHASE5_RIVAL_HQ_PRODUCTION_REPORT.md`',''];report.write_text('\n'.join(lines));print(report)
